### ISSUE TITLE
Create the packagist package

### ISSUE THREAD

**Issue by sroze** [php-enqueue/messenger-adapter#1]
@makasim can you create the `enqueue/messenger-adapter` package on Packagist? And give the according permissions to whoever needs them 😉

**Comment by makasim** [comment]
have you used github's move feature? It should do redirect from https://github.com/sroze/enqueue-bridge to this repo.

**Comment by makasim** [comment]
Give me admin access to the repo and I'll move it (that way all posted links would still work) and do the other things like posting on packagins etc.

**Comment by sroze** [comment]
I did not. It's OK, we will remove the traces of `sroze/enqueue-bridge` 😉

**Comment by sroze** [comment]
I did already refactor the code in this repository so can't really do it anymore.

**Comment by makasim** [comment]
done

**Comment by sroze** [comment]
Thank you!
