### ISSUE TITLE
This transport does not supports envelope items

### ISSUE THREAD

**Issue by sroze** [php-enqueue/messenger-adapter#17]
We should serialize/deserialize the message envelope items via the headers (Symfony's default message serializer does this already). All we should have to do is to set the headers properly from the encoded message :)

**Comment by weaverryan** [comment]
I think this is not valid anymore. The transport `QueueInteropTransport` accepts whatever the configured transport is inside Symfony (via FrameworkBundle). And so, serialization/deserialization of envelopes works fine (because it works fine there).
