### ISSUE TITLE
"amqp" is not supported. Supported "null"

### ISSUE THREAD

**Issue by Lukashab** [php-enqueue/messenger-adapter#3]
Hi, I tried to integrate messenger-adapter to work with my symfony/messenger component. I set up everything according to documentation. I have rabbitmq running on DSN : amqp://rabbit:rabbit@devel_rabbit:5672/%2f so I defined it as `ENQUEUE_DSN` in `.env` file.

The problem is, whenever I run `bin/console messenger:consume-messages amqp` following exception appears : 
```
[LogicException]                                      
  The scheme "amqp" is not supported. Supported "null" 
```

Do you know what could be the cause ? 
Thanks

**Comment by makasim** [comment]
Try installing one of the amqp transports for example 

Composer req enqueue/amqp-bunny

**Comment by Lukashab** [comment]
It solved a problem for me. 
Thanks a lot :)

**Comment by sroze** [comment]
Great to hear. Closing then :)
