### ISSUE TITLE
On exceptions the message should not be requeued?

### ISSUE THREAD

**Issue by malheirosrafa** [php-enqueue/messenger-adapter#34]
On exceptions the [QueueInteropTransport](https://github.com/php-enqueue/messenger-adapter/blob/07046f6bc13ebc338e30fa0d9d1fe36c547d524a/QueueInteropTransport.php#L100)  should not requeue the message instead of rejected it?

If this is the correct behaviour, how can I make the message at least not be rejected, to let te visibility timeout of AWS SQS set the message visible again?

**Comment by makasim** [comment]
Add one more transport specific exception to workaround messenger abstraction.

**Comment by malheirosrafa** [comment]
Can you give me some tips on how can I do it?

**Comment by makasim** [comment]
* catch your domain exception
* throw a special exception that instructs an underlying transport not to do anything. Has to be implemented.

Btw enqueue itself does not get in your way. If you do not catch exception it will be redelivered once visibility timeout. If you catch it you can decide what to do: ack, reject or requeue.

**Comment by malheirosrafa** [comment]
That's the problem, it I'm not catching the exception and it is not being redelivered on visibility timeout.

**Comment by makasim** [comment]
yeap it's because transport is trying to be smart https://github.com/php-enqueue/messenger-adapter/blob/master/QueueInteropTransport.php#L99

**Comment by Markoshd** [comment]
hey, i've got the same problem.  Did u solve your problem @malheirosrafa ? because I could not really understand the explanation give since for me it was the same Post you've made.
@makasim the best way to solve it is to extend the SQS Transport and override the Receive method?
if so, can you post some examples yourself?
