### ISSUE TITLE
Is there a plan to release a new version before Symfony 4.2 release ?

### ISSUE THREAD

**Issue by shulard** [php-enqueue/messenger-adapter#36]
Hello guys !

Since the Symfony 4.2 as entered RC phase and the current stable version of this package is not compatible with it, do you plan to release a new version before the official release of Symfon 4.2 ?

Thanks

PS: and if you need some hands to help here, I'll be glad to give some time 😄.

**Comment by makasim** [comment]
help is very welcome.

**Comment by drgomesp** [comment]
Master should be very close to working with Symfony 4.2 already.

**Comment by shulard** [comment]
I think master works with Symfony 4.2 because the main issue is about the encoder/decoder transformed to a serializer.

Please tell me what I can do to help.

**Comment by drgomesp** [comment]
Well, for now, we can just test master more extensively against Symfony 4.2. Once they officially release it, we can tag it from here. What do you think @makasim ?

**Comment by makasim** [comment]
Sounds like a plan.

**Comment by shulard** [comment]
Ok so I'll update the travis matrix to also test on Symfony beta version.

**Comment by Gnucki** [comment]
Enqueue 0.9 released.
Symfony 4.2 released.
Here is the time to release the krak... 0.2.0 of messenger-adapter! Isn't it?

**Comment by chalasr** [comment]
Yep, please :)

**Comment by makasim** [comment]
https://github.com/php-enqueue/messenger-adapter/releases/tag/0.2.0

**Comment by shulard** [comment]
Thanks @makasim, maybe adding a little release note about the Symfony 4.2 compatibility ?

**Comment by sroze** [comment]
@makasim thank you!
