### ISSUE TITLE
Issue with multiple senders - enveloping same message more than once

### ISSUE THREAD

**Issue by cgonser** [php-enqueue/messenger-adapter#39]
I have multiple senders configured and everything was working fine until I updated to the latest messenger version.

After some debugging, I realized that the message is being enveloped more than once [here](https://github.com/php-enqueue/messenger-adapter/blob/77a596507b0e7b8bbddae573579f81ce7a082959/QueueInteropTransport.php#L153).

I also noticed that the `$message` variable gets redefined [here](https://github.com/php-enqueue/messenger-adapter/blob/77a596507b0e7b8bbddae573579f81ce7a082959/QueueInteropTransport.php#L119) - it was originally an `Envelope` instance containing my original message under the `message` parameter and it becomes an instance of `\Interop\Amqp\Impl\AmqpMessage`, which gets enveloped and returned in the end of this method.

It seems that the issue also started after [this change on the MiddlewareInterface](https://github.com/symfony/messenger/commit/b61ae3a6ec20107a9136805b53659eb101370b80#diff-2464a1b929b3b4bcf55a6104ad89e24e), as the `$envelope` variable now gets redefined after each iteration.

**Comment by ogizanagi** [comment]
See #43
