### ISSUE TITLE
"enqueue.locator" service does not exists

### ISSUE THREAD

**Issue by Umair-Qadeer** [php-enqueue/messenger-adapter#42]
Hi there.
I followed this code example.  
https://stefanoalletti.wordpress.com/2018/11/05/from-rabbitmq-to-phpenqueue-via-symfony-messenger/

When I try to run **"php bin/console messenger:consume mailer"** command I got following error.

> In CheckExceptionOnInvalidReferenceBehaviorPass.php line 86:                                                                                     
>   The service "enqueue.messenger_transport.factory" has a dependency on a non-existent service "enqueue.locator". 

I don't know why enqueue locator is missing. Can anyone help me with this issue?

Thanks.

**Comment by makasim** [comment]
Have you configured enqueue bundle?

**Comment by Umair-Qadeer** [comment]
Ahh, You are right. Thanks
I am new to Symfony and these packages.
Now I am stuck at configurations. :(
Here is my enqueue.yaml config file code

> #config/packages/enqueue.yaml
> enqueue:
>     amqp:
>         transport: 'amqp://guest:guest@localhost:5672'
>     client:
>         transport: ~
>     default_client:
>         transport: ~

Now i am getting Following error:

>   [Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException]  
>   You have requested a non-existent parameter "enqueue.default_client".      

What are these config variable for? Don't know what to do about this.

Thanks again.

**Comment by weaverryan** [comment]
Please let us know if it's still not working

**Comment by dfoster-cb911** [comment]
@Umair-Qadeer mentioned he still had the issue of: 

>[Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException]
You have requested a non-existent parameter "enqueue.default_client".

This is actually something that I am dealing with right now on symfony 4.2 flex. Enqueue bundle and sqs packages are installed, it skips over setting the `enqueue.default_client` service if there is no `$defaultClient` set, which is also only set if there are `$clientNames` available to choose from. 

In my process the client names variable is an empty array, so it never gets set. 

How can I set these for sqs?

**Comment by Umair-Qadeer** [comment]
Hi @dfoster-cb911, 

Try this. This works for me.

```yaml
enqueue:
  default:
    transport: '%env(ENQUEUE_DSN)%'
    client: ~
```

**Comment by dfoster-cb911** [comment]
Ok great, this has worked for me, @Umair-Qadeer . Thank you kindly.

**Comment by Umair-Qadeer** [comment]
No problem. ;)
I have posted this on another issue. you should have found that on google.
