### ISSUE TITLE
Help instruct to install serializer when it's missing

### ISSUE THREAD

**Issue by weaverryan** [php-enqueue/messenger-adapter#45]
If you currently only install this adapter, but do not install the serializer, you'll get this error at container build time:

> The service "enqueue.messenger_transport.factory" has a dependency on a non-existent service  
   "messenger.transport.serializer

Unless you're doing something really custom, the issue will always be the same: you haven't installed the serializer. I think we could add a compiler pass that checks for the `messenger.transport.serializer` service and throws an exception if it's missing (this is similar to what FrameworkExtension does):

> The Messenger serializer transport is missing. Try enabling it or running "composer require symfony/serializer-pack".'

**Comment by devrck** [comment]
Seems a legit request, I will see when I have the time to tackle it if nobody minds.
