### ISSUE TITLE
No transport supports the given DSN "enqueue://default".

### ISSUE THREAD

**Issue by dgoujard** [php-enqueue/messenger-adapter#5]
Hi,

I tryed to use your adapter with redis transporter.
I'm using symfony 4.1 with messenger, i followed steps, when at step 5 i got : 
```
In TransportFactory.php line 37:
                                                            
  No transport supports the given DSN "enqueue://default".  
                                                            

```
I think messenger component isn't connected to enqueue, i checked and enqueue bundle is loaded bundles.php 

It's maybe an messenger change before the release this week ?

**Comment by sroze** [comment]
There are a [few bugs to be fixed in this pull-request](https://github.com/php-enqueue/messenger-adapter/pull/7). Could you check your application with the source code in the PR branch and be sure to clear your cache after installing the messenger adapter?

**Comment by dgoujard** [comment]
@sroze I cloned this repo https://github.com/scarbo87/messenger-adapter, copied files in my vendor directory, cleaned cache but i still got the error

**Comment by sroze** [comment]
I suggest you clone this repo instead, it contains the latest fixes: https://github.com/php-enqueue/messenger-adapter.

**Comment by Gnucki** [comment]
Add this line in your `config/bundles.php` file:
```js
    Enqueue\MessengerAdapter\Bundle\EnqueueAdapterBundle::class => ['all' => true]
```

**Comment by dgoujard** [comment]
I created an clean project to test

```
composer create-project symfony/website-skeleton my_project
cd my_project
composer req symfony/messenger enqueue/messenger-adapter enqueue/redis predis/predis:^1 
editing .env to set ENQUEUE_DSN content
editing config/packages/messenger.yaml to add amqp: enqueue://default
adding "Enqueue\MessengerAdapter\Bundle\EnqueueAdapterBundle::class => ['all' => true]" in config/bundles.php
execute  bin/console messenger:consume-messages amqp
```
I got the error
```
In TransportFactory.php line 37:
                                                            
  No transport supports the given DSN "enqueue://default".  

```                                                            

Now i download master branch and update package un vendor dir, clean the dev cache and it's work (no error message)

**Comment by lpj145** [comment]
same with me: No transport supports the given DSN "amqp://guest:guest@localhost:5672/%2f/messages"."

**Comment by Steveb-p** [comment]
For future visitors, in case they run into the same issue as me when dealing with non-flex Symfony apps: there are two different bundles `Enqueue\MessengerAdapter\Bundle\EnqueueAdapterBundle` and `\Enqueue\Bundle\EnqueueBundle`. Both are required.

**Comment by chdeliens** [comment]
In case this helps anybody (even though this looks unrelated to enqueue), I had the following message on a fresh Symfony 4.2 + messenger app:

`No transport supports the given DSN "amqp://guest:guest@localhost:5672/%2f/messages".`

I fixed the issue by installing the `amqp-pack` bundle from Symfony with:
`composer req amqp`

That package also enforces that you have the `amqp` PHP extension installed and enabled 👍

**Comment by Herz3h** [comment]
`composer require symfony/amqp-messenger` in my case on Symfony 4.4 -> 5.3 upgrade
