### ISSUE TITLE
[REDIS] Redis Factory

### ISSUE THREAD

**Issue by Guikingone** [php-enqueue/messenger-adapter#59]
Hi everyone, 

Small question about the adapter, is there any way to use Redis in a similar way as the `amqp` transport? 

I need to do something quite similar to this: https://medium.com/@dimitri.gritsajuk/symfony-messenger-is-here-but-your-project-is-on-symfony-3-4-no-problem-part-2-204fb18520b6 and I don't find any `RedisTransportFactory` (I've found a `RedisConnectionFactory` but Symfony wait for a TransportFactory instance). 

Thanks again for the support.

**Comment by weaverryan** [comment]
Hi @Guikingone!

I don't think that blog post uses this library - I think it *only* uses the core Symfony Messenger features and (at this moment) Symfony only supports AQMP in core. You can use other transports via this bridge + Enqueue, which is the point of this library actually :).

Cheers!
