### ISSUE TITLE
Bugs in messenger-adapter

### ISSUE THREAD

**Issue by scarbo87** [php-enqueue/messenger-adapter#6]
Hi, i tried to use messenger-adapter and found few bugs:

1. `QueueInteropTransport::send` dont implement `TransportInterface`:
`Compile Error: Declaration of Enqueue\\MessengerAdapter\\QueueInteropTransport::send($message): void must be compatible with Symfony\\Component\\Messenger\\Transport\\SenderInterface::send(Symfony\\Component\\Messenger\\Envelope $envelope)`
1. If options `deliveryDelay` is true, must be call `producer::setDelayStrategy` method

**Comment by sroze** [comment]
Does this mean it works for you? :)
